// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const FIELDGUARD_OWNER_STORAGE_KEY = "fieldguard.owner.id";

function createOwnerId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, (char) =>
    (Number(char) ^ (Math.random() * 16) >> Number(char) / 4).toString(16),
  );
}

function getOrCreateOwnerId(): string {
  try {
    const existing = localStorage.getItem(FIELDGUARD_OWNER_STORAGE_KEY);
    if (existing) return existing;

    const ownerId = createOwnerId();
    localStorage.setItem(FIELDGUARD_OWNER_STORAGE_KEY, ownerId);
    return ownerId;
  } catch {
    // Safari 비공개 모드 등 localStorage 접근 불가 시 폴백
    return createOwnerId();
  }
}

export const FIELDGUARD_OWNER_ID = getOrCreateOwnerId();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      "x-fieldguard-owner-id": FIELDGUARD_OWNER_ID,
    },
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
